FROM node:6.5.0

# Create app directory
RUN mkdir -p /usr/src/react-synthesis
WORKDIR /usr/src/react-synthesis

# Install app dependencies
COPY package.json /usr/src/react-synthesis/
RUN npm install

# Bundle app source
COPY . /usr/src/react-synthesis

# Copy index.html for the dev environment
RUN cp -f index.html.dev /usr/src/react-synthesis/index.html

# Create build
RUN npm run build 

EXPOSE 7700
EXPOSE 3000

#CMD [ "npm", "start" ]
#CMD [ "npm", "run", "build" ]
#ENTRYPOINT npm start
#CMD [ "npm", "run", "dev:hot" ]
CMD npm run build; npm start;npm run dev:hot
